import mongoose from 'mongoose';

/**
 * Expert Research Category Schema
 * Tracks individual research areas within expert context
 */
const ExpertResearchCategorySchema = new mongoose.Schema({
  category: {
    type: String,
    enum: ['historical', 'legislative', 'best_practices', 'case_studies', 'local_landscape', 'technical', 'stakeholder', 'risks', 'opportunities', 'cultural'],
    required: true
  },
  title: { type: String, required: true },
  content: { type: String, required: true },
  sources: [{
    url: String,
    title: String,
    accessed_at: Date,
    relevance_score: Number
  }],
  confidence_score: { type: Number, min: 0, max: 1, default: 0.7 },
  token_count: Number,
  generated_at: { type: Date, default: Date.now }
}, { _id: false });

/**
 * Recommended Module Schema
 * Module recommendations from expert analysis
 */
const RecommendedModuleSchema = new mongoose.Schema({
  module_type: {
    type: String,
    enum: ['standalone', 'user-management', 'client-entity', 'data-collection', 'data-views', 'communications', 'notes', 'calendar', 'tasks', 'workflow', 'reporting', 'inventory', 'custom'],
    default: 'custom'
  },
  title: { type: String, required: true },
  description: String,
  priority: { type: Number, default: 5 },
  rationale: String,
  key_features: [String],
  compliance_link: String
}, { _id: false });

/**
 * Expert Context Schema
 * The comprehensive expertise document generated by Expert Mode
 */
const ExpertContextSchema = new mongoose.Schema({
  summary: { type: String, required: true },
  domain_expertise: { type: String, required: true },
  research_categories: [ExpertResearchCategorySchema],
  key_insights: [String],
  compliance_requirements: [String],
  recommended_modules: [RecommendedModuleSchema],
  total_sources: { type: Number, default: 0 },
  research_depth: {
    type: String,
    enum: ['quick', 'standard', 'comprehensive'],
    default: 'standard'
  },
  deep_research_interaction_id: String,
  generated_at: { type: Date, default: Date.now }
}, { _id: false });

/**
 * Interview Question Schema
 * For both self-interview and human interview tracking
 */
const InterviewQuestionSchema = new mongoose.Schema({
  question_id: { type: String, required: true },
  category: {
    type: String,
    // Flexible to handle various AI-generated categories
    default: 'other'
  },
  question: { type: String, required: true },
  response: String,
  follow_up_questions: [String],
  insights_extracted: [String],
  answered_at: Date,
  answered_by: {
    type: String,
    enum: ['ai_self', 'human'],
    default: 'ai_self'
  }
}, { _id: false });

/**
 * Ideation Document Schema
 * Results of the ideation/consultation phase
 */
const IdeationDocumentSchema = new mongoose.Schema({
  summary: { type: String, required: true },
  interview_mode: {
    type: String,
    enum: ['self_interview', 'human_interview', 'hybrid'],
    default: 'self_interview'
  },
  questions_answered: [InterviewQuestionSchema],
  requirements: {
    functional: [String],
    non_functional: [String],
    constraints: [String],
    assumptions: [String]
  },
  proposed_modules: [{
    module_type: String,
    title: String,
    description: String,
    priority: { type: Number, default: 5 },
    estimated_complexity: { type: String, enum: ['very low', 'low', 'medium', 'high', 'very high'], default: 'medium' },
    dependencies: [String],
    key_features: [String],
    domains: [String],
    requirements_addressed: [String]
  }],
  data_model_outline: {
    entities: [{
      name: String,
      description: String,
      key_fields: [String],
      relationships: [String]
    }]
  },
  workflow_outline: [{
    name: String,
    description: String,
    steps: [String],
    triggers: [String]
  }],
  risk_assessment: [{
    risk: String,
    impact: { type: String, enum: ['low', 'medium', 'high'] },
    mitigation: String
  }],
  generated_at: { type: Date, default: Date.now }
}, { _id: false });

/**
 * Module Generation Result Schema
 * Tracks each generated manifest within the pack
 */
const ModuleResultSchema = new mongoose.Schema({
  manifest_id: { type: String, required: true },
  module_type: { type: String, required: true },
  title: { type: String, required: true },
  description: String,
  order: { type: Number, default: 0 },
  status: {
    type: String,
    enum: ['pending', 'generating', 'completed', 'failed'],
    default: 'pending'
  },
  dependencies: [String],
  domains_count: Number,
  fields_count: Number,
  generation_time_ms: Number,
  error_message: String,
  generated_at: Date
}, { _id: false });

/**
 * Module Pack Schema
 * Groups related manifests created from a single expert+ideation session
 */
const ModulePackSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  description: String,

  // Configuration
  config: {
    region: { type: String, required: true },
    currency: { type: String, default: 'USD' },
    locale: { type: String, default: 'en-US' },
    service_types: [String],
    target_users: [String]
  },

  // Original request
  original_request: {
    prompt: String,
    domains: [String],
    additional_context: String,
    funding_body: String,
    project_name: String
  },

  // Expert Mode output
  expert_context: ExpertContextSchema,

  // Ideation Mode output
  ideation_document: IdeationDocumentSchema,

  // Generated modules
  modules: [ModuleResultSchema],

  // Processing status
  status: {
    type: String,
    enum: ['draft', 'researching', 'ideating', 'generating', 'completed', 'failed', 'partial'],
    default: 'draft'
  },
  current_phase: {
    type: String,
    enum: ['init', 'expert_research', 'ideation', 'module_planning', 'module_generation', 'validation', 'complete'],
    default: 'init'
  },

  // Progress tracking
  progress: {
    expert_mode_complete: { type: Boolean, default: false },
    ideation_complete: { type: Boolean, default: false },
    modules_planned: { type: Number, default: 0 },
    modules_generated: { type: Number, default: 0 },
    modules_failed: { type: Number, default: 0 }
  },

  // Metadata
  created_by: {
    type: String,
    index: true
  },
  visibility: {
    type: String,
    enum: ['PUBLIC', 'PRIVATE'],
    default: 'PRIVATE'
  },
  tags: [String],

  // Error tracking
  errors: [{
    phase: String,
    message: String,
    timestamp: { type: Date, default: Date.now }
  }],

  // Progress log - stores all events from generation for replay/review
  progress_log: [{
    phase: String,
    status: String,
    message: String,
    timestamp: { type: Date, default: Date.now },
    metadata: mongoose.Schema.Types.Mixed
  }]
}, {
  timestamps: true,
  toJSON: {
    transform: (doc, ret) => {
      delete ret._id;
      delete ret.__v;
      return ret;
    }
  }
});

// Indexes
ModulePackSchema.index({ 'config.region': 1 });
ModulePackSchema.index({ status: 1 });
ModulePackSchema.index({ createdAt: -1 });
ModulePackSchema.index({ tags: 1 });
ModulePackSchema.index({ 'modules.manifest_id': 1 });

// Methods
ModulePackSchema.methods.addModule = function(moduleResult) {
  this.modules.push(moduleResult);
  this.progress.modules_generated++;
  return this.save();
};

ModulePackSchema.methods.updatePhase = function(phase) {
  this.current_phase = phase;
  return this.save();
};

ModulePackSchema.methods.markComplete = function() {
  this.status = 'completed';
  this.current_phase = 'complete';
  return this.save();
};

ModulePackSchema.methods.addError = function(phase, message) {
  this.errors.push({ phase, message });
  return this.save();
};

// Statics
ModulePackSchema.statics.findByManifestId = function(manifestId) {
  return this.findOne({ 'modules.manifest_id': manifestId });
};

ModulePackSchema.statics.findPublic = function() {
  return this.find({ visibility: 'PUBLIC' }).sort({ createdAt: -1 });
};

ModulePackSchema.statics.findByUser = function(userId) {
  return this.find({ created_by: userId }).sort({ createdAt: -1 });
};

const ModulePack = mongoose.model('ModulePack', ModulePackSchema);

export default ModulePack;
