/**
 * SecurityAlert Model - Chameleon Protocol
 * 
 * Stores security alerts generated by the Sentinel Agent.
 */

import mongoose from 'mongoose';

const securityAlertSchema = new mongoose.Schema({
  id: {
    type: String,
    required: true,
    unique: true,
    index: true
  },
  // Alert classification
  alert_type: {
    type: String,
    required: true,
    enum: [
      'BULK_ACCESS',
      'AFTER_HOURS',
      'FAILED_LOGINS',
      'PERMISSION_DENIED',
      'CONSENT_VIOLATION',
      'SUSPICIOUS_PATTERN',
      'DATA_EXFILTRATION',
      'OTHER'
    ],
    index: true
  },
  severity: {
    type: String,
    enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
    default: 'MEDIUM',
    index: true
  },
  // Who triggered the alert
  user_id: {
    type: String,
    required: true,
    index: true
  },
  // Description
  title: {
    type: String,
    required: true
  },
  description: {
    type: String
  },
  // Evidence
  evidence: {
    action_count: Number,
    time_window: String,
    sample_events: [mongoose.Schema.Types.Mixed]
  },
  // Automated action taken
  auto_action: {
    type: String,
    enum: ['NONE', 'LOGGED', 'ALERTED', 'REVIEWED', 'TEMP_LOCKED', 'FROZEN'],
    default: 'LOGGED'
  },
  // Resolution
  is_resolved: {
    type: Boolean,
    default: false,
    index: true
  },
  resolved_by: String,
  resolved_at: Date,
  resolution_notes: String,
  // False positive tracking
  is_false_positive: {
    type: Boolean,
    default: false
  }
}, {
  timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' }
});

// Index for dashboard queries
securityAlertSchema.index({ severity: 1, is_resolved: 1, created_at: -1 });

/**
 * Resolve an alert
 */
securityAlertSchema.methods.resolve = async function(userId, notes, isFalsePositive = false) {
  this.is_resolved = true;
  this.resolved_by = userId;
  this.resolved_at = new Date();
  this.resolution_notes = notes;
  this.is_false_positive = isFalsePositive;
  return this.save();
};

/**
 * Get unresolved alerts
 */
securityAlertSchema.statics.getUnresolved = async function(severity = null) {
  const query = { is_resolved: false };
  if (severity) query.severity = severity;
  return this.find(query).sort({ created_at: -1 });
};

/**
 * Get alerts for a user
 */
securityAlertSchema.statics.getForUser = async function(userId, includeResolved = false) {
  const query = { user_id: userId };
  if (!includeResolved) query.is_resolved = false;
  return this.find(query).sort({ created_at: -1 });
};

const SecurityAlert = mongoose.model('SecurityAlert', securityAlertSchema);

export default SecurityAlert;
