/**
 * Application Packager - Chameleon Protocol
 * 
 * Packages generated code into a downloadable application:
 * 1. Creates directory structure
 * 2. Writes all generated files
 * 3. Creates ZIP archive
 * 4. Generates documentation
 */

import archiver from 'archiver';
import { Readable } from 'stream';

class ApplicationPackager {
  constructor() {
    this.files = [];
  }

  async packageApplication(generatedCode, architecture, onProgress) {
    onProgress?.({ 
      status: 'package:starting', 
      detail: 'Packaging application for download...' 
    });

    this.files = generatedCode.files;

    const documentation = await this.generateDocumentation(architecture, generatedCode);
    this.files.push(...documentation);

    const manifest = this.createManifest(architecture, generatedCode);
    this.files.push(manifest);

    onProgress?.({ 
      status: 'package:creating-archive', 
      detail: `Creating ZIP archive with ${this.files.length} files...` 
    });

    const zipBuffer = await this.createZipArchive();

    onProgress?.({ 
      status: 'package:complete', 
      detail: `Application packaged successfully. Size: ${(zipBuffer.length / 1024 / 1024).toFixed(2)} MB` 
    });

    return {
      zipBuffer,
      filename: this.generateFilename(architecture),
      fileCount: this.files.length,
      size: zipBuffer.length
    };
  }

  async generateDocumentation(architecture, generatedCode) {
    const docs = [];

    docs.push({
      path: 'README.md',
      content: this.generateReadme(architecture, generatedCode)
    });

    docs.push({
      path: 'ARCHITECTURE.md',
      content: this.generateArchitectureDoc(architecture)
    });

    docs.push({
      path: 'API.md',
      content: this.generateAPIDoc(architecture)
    });

    docs.push({
      path: 'DEPLOYMENT.md',
      content: this.generateDeploymentDoc(architecture)
    });

    return docs;
  }

  generateReadme(architecture, generatedCode) {
    return `# ${architecture.architecture.domain} Application

Auto-generated by Chameleon Protocol

## Overview

This application was automatically generated based on deep research and domain analysis for ${architecture.architecture.domain} in ${architecture.architecture.region}.

## Modules

${architecture.modules.map(m => `- **${m.module_type}**: ${m.rationale}`).join('\n')}

## Quick Start

### Prerequisites

- Node.js 18+
- PostgreSQL 14+
- npm or yarn

### Installation

\`\`\`bash
# Install dependencies
npm install

# Set up environment variables
cp .env.example .env
# Edit .env with your configuration

# Run database migrations
npm run migrate

# Start development server
npm run dev
\`\`\`

### Production Deployment

See [DEPLOYMENT.md](./DEPLOYMENT.md) for detailed deployment instructions.

## Project Structure

\`\`\`
.
├── backend/
│   ├── src/
│   │   ├── routes/      # API routes
│   │   ├── controllers/ # Request handlers
│   │   ├── services/    # Business logic
│   │   ├── models/      # Data models
│   │   └── middleware/  # Express middleware
│   └── tests/           # Backend tests
├── frontend/
│   ├── src/
│   │   ├── components/  # React components
│   │   ├── pages/       # Page components
│   │   ├── services/    # API clients
│   │   └── types/       # TypeScript types
│   └── tests/           # Frontend tests
├── database/
│   └── migrations/      # SQL migrations
└── docs/                # Documentation

\`\`\`

## Generated Files

- **Total Files**: ${generatedCode.summary.totalFiles}
- **By Type**: ${Object.entries(generatedCode.summary.byType).map(([type, count]) => `${type}: ${count}`).join(', ')}

## API Documentation

See [API.md](./API.md) for complete API documentation.

## Architecture

See [ARCHITECTURE.md](./ARCHITECTURE.md) for detailed architecture documentation.

## License

Generated application - customize as needed.

## Support

This application was generated by Chameleon Protocol. For questions or issues, refer to the documentation or contact your administrator.
`;
  }

  generateArchitectureDoc(architecture) {
    return `# Architecture Documentation

## System Overview

**Domain**: ${architecture.architecture.domain}
**Region**: ${architecture.architecture.region}
**Generated**: ${architecture.architecture.timestamp}
**Modules**: ${architecture.architecture.moduleCount}

## Module Architecture

${architecture.modules.map(m => `
### ${m.module_type}

**Priority**: ${m.priority}
**Rationale**: ${m.rationale}

**Configuration**:
\`\`\`json
${JSON.stringify(architecture.configurations[m.module_type], null, 2)}
\`\`\`
`).join('\n')}

## Database Schema

### Tables

${architecture.database.tables?.map(t => `
#### ${t.name}

${t.description || ''}

**Columns**:
${t.columns?.map(c => `- \`${c.name}\` (${c.type})${c.primary_key ? ' [PK]' : ''}${c.foreign_key ? ` [FK → ${c.foreign_key}]` : ''}`).join('\n')}

**Indexes**:
${t.indexes?.map(i => `- ${i.name}: ${i.columns.join(', ')}${i.unique ? ' [UNIQUE]' : ''}`).join('\n') || 'None'}
`).join('\n') || 'No tables defined'}

### Relationships

${architecture.database.relationships?.map(r => 
  `- ${r.from_table}.${r.from_column} → ${r.to_table}.${r.to_column} (${r.relationship_type})`
).join('\n') || 'No relationships defined'}

## Technology Stack

- **Backend**: Node.js, Express
- **Frontend**: React, TypeScript, Tailwind CSS
- **Database**: PostgreSQL
- **Testing**: Jest/Vitest
- **Authentication**: JWT

## Design Principles

1. **Modular Architecture**: Each module is self-contained and can be developed independently
2. **RESTful API**: Standard REST conventions for all endpoints
3. **Type Safety**: TypeScript throughout for better developer experience
4. **Scalability**: Database design supports horizontal scaling
5. **Security**: Authentication and authorization built-in
`;
  }

  generateAPIDoc(architecture) {
    return `# API Documentation

**Base URL**: \`${architecture.api.base_url || '/api/v1'}\`

## Authentication

${architecture.api.authentication ? `
**Type**: ${architecture.api.authentication.type}

### Authentication Endpoints

${architecture.api.authentication.endpoints?.map(e => `
#### ${e.method} ${e.path}

${e.description}

**Request**:
\`\`\`json
${JSON.stringify(e.request_body, null, 2)}
\`\`\`

**Response**:
\`\`\`json
${JSON.stringify(e.response, null, 2)}
\`\`\`
`).join('\n') || ''}
` : 'No authentication configured'}

## Endpoints

${architecture.api.endpoints?.map(e => `
### ${e.method} ${e.path}

**Module**: ${e.module}
**Description**: ${e.description}
**Auth Required**: ${e.auth_required ? 'Yes' : 'No'}
${e.permissions?.length ? `**Permissions**: ${e.permissions.join(', ')}` : ''}

${e.query_params?.length ? `
**Query Parameters**:
${e.query_params.map(p => `- \`${p.name}\` (${p.type})${p.required ? ' [required]' : ''}: ${p.description}`).join('\n')}
` : ''}

${e.request_body ? `
**Request Body**:
\`\`\`json
${JSON.stringify(e.request_body, null, 2)}
\`\`\`
` : ''}

**Response**:

Success:
\`\`\`json
${JSON.stringify(e.response?.success, null, 2)}
\`\`\`

Error:
\`\`\`json
${JSON.stringify(e.response?.error, null, 2)}
\`\`\`
`).join('\n---\n') || 'No endpoints defined'}

## Error Codes

- **400**: Bad Request - Invalid input
- **401**: Unauthorized - Authentication required
- **403**: Forbidden - Insufficient permissions
- **404**: Not Found - Resource not found
- **500**: Internal Server Error - Server error

## Rate Limiting

Rate limiting may be applied to prevent abuse. Default limits:
- 100 requests per minute per IP
- 1000 requests per hour per authenticated user
`;
  }

  generateDeploymentDoc(architecture) {
    return `# Deployment Guide

## Prerequisites

- Node.js 18+ installed
- PostgreSQL 14+ installed and running
- npm or yarn package manager
- (Optional) Docker and Docker Compose

## Environment Configuration

Create a \`.env\` file in the root directory:

\`\`\`env
# Database
DATABASE_URL=postgresql://user:password@localhost:5432/dbname

# Server
PORT=3000
NODE_ENV=production

# Authentication
JWT_SECRET=your-secret-key-here
JWT_EXPIRES_IN=7d

# (Add other environment variables as needed)
\`\`\`

## Database Setup

### Option 1: Manual Setup

\`\`\`bash
# Create database
createdb your_database_name

# Run migrations
npm run migrate
\`\`\`

### Option 2: Docker

\`\`\`bash
# Start PostgreSQL with Docker
docker-compose up -d postgres

# Run migrations
npm run migrate
\`\`\`

## Application Deployment

### Development

\`\`\`bash
# Install dependencies
npm install

# Start development server
npm run dev
\`\`\`

### Production

\`\`\`bash
# Install dependencies
npm install --production

# Build frontend
npm run build

# Start production server
npm start
\`\`\`

### Docker Deployment

\`\`\`bash
# Build and start all services
docker-compose up -d

# View logs
docker-compose logs -f

# Stop services
docker-compose down
\`\`\`

## Monitoring

- Application logs: \`logs/app.log\`
- Error logs: \`logs/error.log\`
- Access logs: \`logs/access.log\`

## Backup

### Database Backup

\`\`\`bash
# Create backup
pg_dump -U user dbname > backup.sql

# Restore backup
psql -U user dbname < backup.sql
\`\`\`

## Security Checklist

- [ ] Change default JWT secret
- [ ] Enable HTTPS in production
- [ ] Configure CORS properly
- [ ] Set up rate limiting
- [ ] Enable database backups
- [ ] Configure firewall rules
- [ ] Set up monitoring and alerts

## Scaling

For high-traffic applications:

1. **Database**: Use connection pooling, read replicas
2. **Application**: Deploy multiple instances behind load balancer
3. **Caching**: Add Redis for session storage and caching
4. **CDN**: Serve static assets via CDN

## Troubleshooting

### Common Issues

**Database connection failed**
- Check DATABASE_URL in .env
- Ensure PostgreSQL is running
- Verify network connectivity

**Port already in use**
- Change PORT in .env
- Kill process using the port

**Build errors**
- Clear node_modules and reinstall
- Check Node.js version compatibility
`;
  }

  createManifest(architecture, generatedCode) {
    return {
      path: 'chameleon-manifest.json',
      content: JSON.stringify({
        generator: 'Chameleon Protocol',
        version: '1.0.0',
        generated: new Date().toISOString(),
        architecture: architecture.architecture,
        modules: architecture.modules,
        fileCount: generatedCode.summary.totalFiles,
        filesByType: generatedCode.summary.byType
      }, null, 2)
    };
  }

  async createZipArchive() {
    return new Promise((resolve, reject) => {
      const archive = archiver('zip', {
        zlib: { level: 9 }
      });

      const chunks = [];

      archive.on('data', (chunk) => chunks.push(chunk));
      archive.on('end', () => resolve(Buffer.concat(chunks)));
      archive.on('error', reject);

      for (const file of this.files) {
        archive.append(file.content, { name: file.path });
      }

      archive.finalize();
    });
  }

  generateFilename(architecture) {
    const domain = architecture.architecture.domain
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-');
    const timestamp = new Date().toISOString().split('T')[0];
    return `${domain}-app-${timestamp}.zip`;
  }
}

export { ApplicationPackager };
